### ISSUE TITLE
kurshtml.edu.pl

### ISSUE THREAD

**Issue by michal-perlakowski** [CodersCommunity/awesome-links#13]
http://www.kurshtml.edu.pl/ zdecydowanie nie jest "awesome", lepszy jest np. http://how2html.pl/

**Comment by Comandeer** [comment]
To radzę sobie porównać zakres materiału. Owszem, kurshtml.edu.pl nie jest tak "świeży", ale How2HTML raptem pokrywa całkowity materiał dla początkujących.

Zresztą np. tutaj: http://how2html.pl/div-box-model/ → jakoś dziwnie opisany ten box model… a o border-box wgl nic nie ma.

Prawda jest taka, że w Polsce nie ma super aktualnego i całościowego kursu HTML.

Proponuję dołączenie How2HTML do listy przy zachowaniu KursHTML.edu.pl i tyle ;)

**Comment by michal-perlakowski** [comment]
@Comandeer Zgodzę się z tym, że w Polsce nie ma porządnego kursu HTML, aczkolwiek jeśli ktoś chce się jakoś bardziej rozwijać w tym kierunku to znajomość angielskiego jest konieczna.

KursHTML.edu.pl jest po prostu przestarzały i uczy złych praktyk - używania rzeczy, które były już chyba w HTML 4.01 odradzane, typu atrybut `align`, `<b>`, `<font size>`. Według mnie nie ma znaczenie ilość, ale jakość, więc lepiej skorzystać z jakiegoś mniej obszernego, ale bardziej aktualnego kursu.

**Comment by Comandeer** [comment]
> KursHTML.edu.pl jest po prostu przestarzały i uczy złych praktyk

To radzę jeszcze raz spojrzeć do tego kursu, bo jest tam ładnie wytłumaczone czemu te rzeczy są odradzane: http://www.kurshtml.edu.pl/html/wysrodkowanie,tekst.html → jest odpowiednia notka. Pewne rzeczy znajdują się tam z encyklopedycznej staranności.
Pomijam fakt, że `b` nigdy nie był odradzany przez specyfikację HTML i w HTML5 dodatkowo nabrał konkretnego znaczenia semantycznego.

**Comment by michal-perlakowski** [comment]
> Pewne rzeczy znajdują się tam z encyklopedycznej staranności.

A to jest encyklopedia czy kurs?

Z `b` może rzeczywiście jest tak jak mówisz, ale `align` zdecydowanie nie powinien być używany, a przy jego [pierwszym wystąpieniu w kursie](http://www.kurshtml.edu.pl/html/paragraf,zielony.html) nie ma żadnej notki o tym, że nie jest zalecany. Po co uczyć się o czymś, czego i tak się nie będzie używać? Jeśli już to miałoby tam być z "encyklopedycznej staranności", to mogłoby być gdzieś na końcu kursu, jako ciekawostka. Uczyłem się HTMLa z tego kursu i pamiętam, że zawsze mnie denerwowało ostrzeżenie: "Ten element jest zdeprecjonowany przez specyfikację HTML 4.01 - zaleca się stosowanie stylów." - jeśli tak to po co o tym piszą? Nie przyszedłem tam uczyć się historii, tylko HTMLa.

A kiedy patrzę na takie rzeczy jak ten skrypt [tutaj](http://www.kurshtml.edu.pl/html/nowe_elementy_html5,html5.html) to w ogóle nie wiem jak to skomentować. Chyba mogłoby to posłużyć jako antyprzykład programowania zgodnie z zasadą DRY.

**Comment by Comandeer** [comment]
W taki sam sposób można się przywalać do różnych rzeczy z How2HTML ;) Żaden z tych kursów nie jest idealny, jednak dalej uważam, że są to jedne z najlepszych w Polsce.

W sumie ubolewam, że kurs od BrowseHappy.pl się nie rozwinął.
