### ISSUE TITLE
Jeden Pull Request = 1 link.

### ISSUE THREAD

**Issue by Comandeer** [CodersCommunity/awesome-links#3]
Nie wiem czy to nie jest zbyt rygorystyczne. A jakbym np chciał dodać z 5 linków? 5 PR?

**Comment by efik** [comment]
Hmm racja :) 
@Comandeer, może  1 commit odpowiada 1 linkowi?

**Comment by Comandeer** [comment]
To już brzmi o wiele lepiej ;)

On Sun, May 24, 2015 at 12:02 PM, Krzysztof Pazdur <notifications@github.com

**Comment by efik** [comment]
Gotowe :+1:
